-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.config (
  key text NOT NULL,
  value jsonb NOT NULL,
  description text,
  category text NOT NULL DEFAULT 'general',
  is_system boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT config_pkey PRIMARY KEY (key)
);
CREATE TABLE public.budgets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  empresa_id integer NOT NULL DEFAULT 1 CHECK (empresa_id = 1),
  tariff_id uuid NOT NULL,
  json_tariff_data jsonb NOT NULL,
  client_type text NOT NULL CHECK (client_type = ANY (ARRAY['particular'::text, 'autonomo'::text, 'empresa'::text])),
  client_name text NOT NULL,
  client_nif_nie text,
  client_phone text,
  client_email text,
  client_web text,
  client_address text,
  client_postal_code text,
  client_locality text,
  client_province text,
  client_acceptance boolean DEFAULT false,
  json_budget_data jsonb NOT NULL,
  status text NOT NULL DEFAULT 'borrador'::text CHECK (status = ANY (ARRAY['borrador'::text, 'pendiente'::text, 'enviado'::text, 'aprobado'::text, 'rechazado'::text, 'caducado'::text])),
  total numeric NOT NULL DEFAULT 0.00,
  iva numeric NOT NULL DEFAULT 0.00,
  base numeric NOT NULL DEFAULT 0.00,
  pdf_url text,
  start_date date,
  end_date date,
  validity_days integer DEFAULT 30 CHECK (validity_days > 0 AND validity_days <= 365),
  user_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT budgets_pkey PRIMARY KEY (id),
  CONSTRAINT budgets_tariff_id_fkey FOREIGN KEY (tariff_id) REFERENCES public.tariffs(id),
  CONSTRAINT budgets_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.issuers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  company_id integer NOT NULL DEFAULT 1,
  issuers_type text NOT NULL CHECK (issuers_type = ANY (ARRAY['empresa'::text, 'autonomo'::text])),
  issuers_name text NOT NULL,
  issuers_nif text NOT NULL,
  issuers_address text NOT NULL,
  issuers_postal_code text,
  issuers_locality text,
  issuers_province text,
  issuers_country text DEFAULT 'España'::text,
  issuers_phone text,
  issuers_email text CHECK (issuers_email IS NULL OR issuers_email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text),
  issuers_web text,
  issuers_irpf_percentage numeric CHECK (issuers_irpf_percentage >= 0::numeric AND issuers_irpf_percentage <= 100::numeric),
  issuers_logo_url text,
  issuers_note text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT issuers_pkey PRIMARY KEY (id),
  CONSTRAINT emisores_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.tariffs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  empresa_id integer NOT NULL DEFAULT 1 CHECK (empresa_id = 1),
  title text NOT NULL,
  description text,
  logo_url text,
  name text NOT NULL,
  nif text,
  address text,
  contact text,
  summary_note text,
  conditions_note text,
  legal_note text,
  template text,
  primary_color text DEFAULT '#000000'::text,
  secondary_color text DEFAULT '#666666'::text,
  status text NOT NULL DEFAULT 'Activa'::text CHECK (status = ANY (ARRAY['Activa'::text, 'Inactiva'::text])),
  validity integer DEFAULT 30 CHECK (validity > 0 AND validity <= 365),
  json_tariff_data jsonb NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  user_id uuid NOT NULL,
  ivas_presentes ARRAY DEFAULT '{}'::numeric[],
  is_template boolean NOT NULL DEFAULT false,
  CONSTRAINT tariffs_pkey PRIMARY KEY (id),
  CONSTRAINT tariffs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['superadmin'::text, 'admin'::text, 'vendedor'::text])),
  empresa_id integer NOT NULL DEFAULT 1 CHECK (empresa_id = 1),
  nombre text NOT NULL,
  email text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'pending'::text])),
  invited_by uuid,
  last_login timestamp with time zone,
  apellidos text,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT users_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES public.users(id)
);